laravel/app/Http/routes.php
laravel/database/migrations/initial_structure.sql
laravel/database/seeds/DatabaseSeeder.php
laravel/database/seeds/UsersTableSeeder.php
laravel/resources/views/auth/login.blade.php
laravel/resources/views/layouts/app.blade.php

create middleware for non registered user

---

laravel/app/Http/AdminControllers/QuestionController.php
laravel/resources/views/question_views/create.blade.php
laravel/resources/views/question_views/edit.blade.php

Fix question create page error behaviour.

---

laravel/resources/views/user_views/index.blade.php

add create button

---

laravel/database/migrations/2017_10_23_000002_update_question_table.php

migration changed

---

laravel/app/Http/AdminControllers/QuestionController.php

fix create/edit answer

---

laravel/app/Http/AdminControllers/QuestionController.php
laravel/resources/views/question_views/index.blade.php

sort and filter question function added

---

laravel/app/Http/APIControllers/StudentsTrackingController.php
laravel/app/Http/Kernel.php
laravel/app/Http/Middleware/VerifyJWTToken.php
laravel/app/Http/api-routes.php
laravel/app/StudentsTracking.php
laravel/database/migrations/2017_10_23_175729_create_students_tracking_table.php

Create progress tracking action

---

laravel/app/Http/AdminControllers/StudentController.php
laravel/app/Http/routes.php
laravel/app/Student.php
laravel/resources/views/layouts/app.blade.php
laravel/resources/views/student_view/index.blade.php
laravel/resources/views/student_view/show.blade.php

Students statistics functionality

---

laravel/app/Http/AdminControllers/SettingController.php
laravel/app/Http/routes.php
laravel/app/Setting.php
laravel/database/migrations/2018_01_18_141050_create_settings_table.php
laravel/resources/views/layouts/app.blade.php
laravel/resources/views/setting_views/index.blade.php

Create settings page

---

laravel/app/Http/AdminControllers/ReportErrorController.php
laravel/app/Http/routes.php
laravel/resources/views/error_report_views/index.blade.php
laravel/resources/views/layouts/app.blade.php

Report error functionality page

---

laravel/database/migrations/2018_01_30_195853_update_report_errors_table.php

 convert comment field to text from varchar255

---

laravel/app/Http/APIControllers/ProfileController.php
laravel/app/Http/api-routes.php
laravel/database/migrations/2018_01_30_222601_update_students_table.php

profile api students

---

laravel/app/Http/AdminControllers/LessonController.php
laravel/app/Http/AdminControllers/LevelController.php
laravel/app/Http/AdminControllers/TopicController.php
laravel/app/Http/AdminControllers/UnitController.php
laravel/composer.json
laravel/composer.lock
laravel/database/migrations/2018_01_30_222602_update_dependency_fields.php
laravel/resources/views/lesson_views/create.blade.php
laravel/resources/views/lesson_views/edit.blade.php
laravel/resources/views/lesson_views/index.blade.php
laravel/resources/views/level_views/create.blade.php
laravel/resources/views/level_views/edit.blade.php
laravel/resources/views/level_views/index.blade.php
laravel/resources/views/topic_views/create.blade.php
laravel/resources/views/topic_views/edit.blade.php
laravel/resources/views/topic_views/index.blade.php
laravel/resources/views/unit_views/create.blade.php
laravel/resources/views/unit_views/edit.blade.php
laravel/resources/views/unit_views/index.blade.php

Dependency field modification.

---

laravel/app/Http/APIControllers/ProfileController.php
laravel/app/Student.php

add validation

---

laravel/app/Http/AdminControllers/QuestionController.php
laravel/database/migrations/2018_01_31_222600_update_question_table.php
laravel/resources/views/question_views/create.blade.php
laravel/resources/views/question_views/edit.blade.php
laravel/resources/views/question_views/show.blade.php

Answer smart check

---

laravel/app/Http/AdminControllers/LessonController.php
laravel/database/migrations/2018_02_04_195853_update_lesson_table.php
laravel/resources/views/lesson_views/create.blade.php
laravel/resources/views/lesson_views/edit.blade.php
laravel/resources/views/lesson_views/index.blade.php

Lesson in development

---

laravel/app/Http/AdminControllers/StudentController.php
laravel/app/Http/routes.php
laravel/app/Student.php
laravel/database/migrations/2018_02_04_195854_update_students_table.php
laravel/resources/views/student_view/index.blade.php

Allow to raise participants to super participants

---

laravel/app/Http/APIControllers/TopicController.php
laravel/app/Http/api-routes.php

Test out functionality

---

ci/src/app/lesson/lesson.component.css
ci/src/app/lesson/lesson.component.html
ci/src/app/lesson/lesson.component.ts
ci/src/styles.scss

CI: Add charts(A1, A4, A5)

---

ci/src/app/_components/welcome/try/try.component.ts
ci/src/app/_components/welcome/welcome.component.html
ci/src/app/_components/welcome/welcome.component.scss
ci/src/app/_components/welcome/welcome.component.ts

CI: fix try component #177
